### ISSUE TITLE
Ideas to promote the project

### ISSUE THREAD

**Issue by noraj** [Optixal/GCTF2017-Scoreboard#1]
Some ideas : 
- add tags to the repository like ctf, ctf-scoreboard, ctf-platform, etc...
- make screenshots
- provide documentation or at least install steps

You will be soon linked here http://list.rawsec.ml/ctf_platforms.html

**Comment by Optixal** [comment]
Hey Noraj, thx for the solid ideas, will definitely improve on the platform and repo.

The scoreboard was an ad-hoc project that was quickly whipped up in a couple of hours for an internal CTF, so didn't pay much attention to the documentation haha

And thx for listing our project, will look forward in seeing it on your site.
